wandItem: BLAZE_ROD
wandName: "&6Magic Wand"
wandLore:
- "&5Click to cast a spell"
- "Press Q to select a spell"

spells:
  fireball:
    disabled: false
    level: 2
    recipe:
    - FIREWORK_CHARGE
    - REDSTONE
    - NETHER_STALK
  shoot:
    disabled: false
    level: 1
    recipe:
    - TNT
    - REDSTONE
    - NETHER_STALK
  lightning:
    disabled: false
    level: 2
    recipe:
    - SULPHUR
    - REDSTONE
    - NETHER_STALK
  poison:
    disabled: false
    level: 1
    recipe:
    - SPIDER_EYE
    - REDSTONE
    - NETHER_STALK
  abilityStealer:
    disabled: false
    level: 3
    recipe:
    - REDSTONE
    - NETHER_STALK
    - NETHER_STAR
  miner:
    disabled: false
    level: 3
    recipe:
    - REDSTONE
    - NETHER_STALK
    - DIAMOND_PICKAXE
  #THROW BLOCKS